<?php
$router->define([	
	''=>'Controllers/common/home.php',
	'admin'=>"Controllers/common/home.php",
	'logout'=>'Controllers/auth/logout.php',
	'index.php'=>'Controllers/common/home.php',
	'index'=>'Controllers/common/home.php',
	'login'=>'Controllers/auth/login.php',
	'registration'=>'Controllers/auth/registration.php',
	'verifymsg'=>'Views/users/unVerifiedUser.view.php',
	'verify'=>'Controllers/auth/verifyRegistration.php',
	'gmail'=>'Controllers/auth/GmailRegistration.php'
]);
?>