CREATE TABLE books(bid INT PRIMARY KEY AUTO_INCREMENT,
	book_name VARCHAR(250) NOT NULL,
	author_name VARCHAR(150) NOT NULL,
	edition VARCHAR(150) NOT NULL,
	cover_image_name VARCHAR(150) NOT NULL,
	last_modify TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
	