CREATE TABLE users(uid INT PRIMARY KEY AUTO_INCREMENT,
	email_id VARCHAR(650) UNIQUE,
	password VARCHAR(300) NOT NULL,
	user_name VARCHAR(250) NOT NULL,
	verified_id BOOLEAN DEFAULT FALSE,
	last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	provider_id VARCHAR(500) NULL,
	type INT DEFAULT '1');